'use client';
import {useEffect,useState} from 'react';
import {Clock3,FileText} from 'lucide-react';
import {PageHero} from '@/components/ui/primitives.jsx';
/* What the person has actually applied to, read back from local storage: the
   receipt half of the lead flow. */
export function ApplicationsPage({go}){const [records,setRecords]=useState([]);useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem('dcw-enquiries-v1')||'[]'))}catch{}},[]);return <main id="main" tabIndex={-1} className="listing-page"><PageHero tone="forest" kicker="YOUR ACTIVITY" title={<>Applications <em>&amp; updates.</em></>} lead="Every enquiry and application created on this device, with the stage it has reached." pills={<><span><FileText/>{records.length} in progress</span><span><Clock3/>Updated live</span></>}/><div className="container app-timeline">{records.map(r=><article key={r.id}><span className="entity-mark">{r.title.slice(0,2).toUpperCase()}</span><div><small>{r.kind||'Enquiry'} • {r.id}{r.course?` • ${r.course}`:''}</small><h2>{r.title}</h2><div className="timeline-line"><i className="done"/><i/><i/><i/></div><div className="timeline-labels"><span>Submitted</span><span>Contact</span><span>Documents</span><span>Decision</span></div></div><button className="btn outline" aria-label={`Updates on ${r.title}`} onClick={()=>go('/notifications')}>Updates</button></article>)}<article className="is-sample"><span className="entity-mark">AU</span><div><small>ONLINE MBA • AMITY ONLINE <b className="sample-tag">SAMPLE</b></small><h2>Application in review</h2><div className="timeline-line"><i className="done"/><i className="done"/><i/><i/></div><div className="timeline-labels"><span>Enquiry sent</span><span>Counsellor called</span><span>Documents</span><span>Confirmed</span></div></div><button className="btn outline" aria-label="View the sample Amity Online application" onClick={()=>go('/distance/university/amity-online')}>View</button></article><article className="is-sample"><span className="entity-mark">HF</span><div><small>RELATIONSHIP EXECUTIVE • HDFC SALES <b className="sample-tag">SAMPLE</b></small><h2>Interview details received</h2><div className="timeline-line"><i className="done"/><i className="done"/><i className="done"/><i/></div><div className="timeline-labels"><span>Applied</span><span>Shortlisted</span><span>Interview</span><span>Offer</span></div></div><button className="btn outline" aria-label="View the sample HDFC Sales application" onClick={()=>go('/jobs/bpo-voice-associate-noida')}>View</button></article></div></main>}

export default ApplicationsPage;
