'use client';
import {ArrowRight,BookOpen,BriefcaseBusiness,Building2,Check,ChevronDown,Compass,GraduationCap,Heart,MapPin,Search,ShieldCheck,Sparkles,Star,TrendingUp} from 'lucide-react';
import {useParams,useRouter} from 'next/navigation';
import './concept.css';

const concepts={
 a:{name:'Editorial Trust',code:'A',strap:'Calm, human and authoritative',eyebrow:'YOUR NEXT MOVE, MADE VISIBLE',title:<>Education decisions,<br/><i>made beautifully clear.</i></>,body:'Courses, colleges and careers—researched deeply, compared honestly, and explained by people who understand the decision.',primary:'Explore your options',secondary:'Speak to an expert'},
 b:{name:'Decision Atlas',code:'B',strap:'Graphic, ownable and product-led',eyebrow:'FROM CONFUSION TO A CLEAR NEXT STEP',title:<>See the whole path.<br/><i>Choose your next move.</i></>,body:'One intelligent map for every decision between school, degree and first job—with the facts that actually matter.',primary:'Build my path',secondary:'Explore the platform'},
 c:{name:'Bold Utility',code:'C',strap:'Energetic, direct and conversion-led',eyebrow:'PADHAI SE PLACEMENT TAK',title:<>Less searching.<br/><i>More moving forward.</i></>,body:'Verified options, clear costs and useful tools for students ready to make their next move.',primary:'Start exploring',secondary:'See how it works'}
};

export default function Concept(){const {variant}=useParams(),router=useRouter();const v=concepts[variant]||concepts.a;return <main className={`concept concept-${variant}`}>
  <div className="concept-bar"><span>DCW DESIGN STUDY • {v.code}</span><b>{v.name}</b><small>{v.strap}</small><div>{Object.entries(concepts).map(([k,x])=><button className={k===variant?'active':''} onClick={()=>router.push(`/concepts/${k}`)} key={k}>{x.code}</button>)}</div></div>
  <header className="concept-header"><button className="concept-logo"><span><i/></span><b>DCW</b></button><nav><button>Distance</button><button>Colleges</button><button>Jobs</button></nav><div className="head-actions"><button className="search-trigger"><Search/>Search anything</button><button className="saved"><Heart/></button><button className="concept-cta">Talk to us <ArrowRight/></button></div></header>
  <section className="concept-hero"><div className="concept-copy"><span className="concept-eyebrow">{v.eyebrow}</span><h1>{v.title}</h1><p>{v.body}</p><div className="concept-actions"><button className="big-primary">{v.primary}<ArrowRight/></button><button className="big-secondary">{v.secondary}</button></div><div className="concept-proof"><span><b>250+</b><small>verified institutions</small></span><span><b>50k</b><small>students guided</small></span><span><b>4.8</b><small>student rating</small></span></div></div><HeroVisual variant={variant}/></section>
  <section className="concept-paths"><div className="section-intro"><span>THREE JOURNEYS. ONE TRUSTED PLACE.</span><h2>Where are you heading next?</h2><p>Choose a path. The whole experience adapts around your goal.</p></div><div className="concept-cards"><PathCard icon={<BookOpen/>} n="01" title="Complete school or earn a degree" meta="Distance Courses Wala" accent="mint"/><PathCard icon={<Building2/>} n="02" title="Find the right regular college" meta="Colleges Wala" accent="gold"/><PathCard icon={<BriefcaseBusiness/>} n="03" title="Build skills and get hired" meta="Berojgar Bharat" accent="coral"/></div></section>
  <section className="concept-feature"><div className="feature-copy"><span>DECISIONS NEED MORE THAN A LIST</span><h2>Compare the facts.<br/>Understand the trade-offs.</h2><p>We bring recognition, fees, flexibility and outcomes into one honest view—so you can decide with confidence.</p><button>See how comparison works <ArrowRight/></button></div><div className="compare-preview"><div className="compare-head"><span>BOARD COMPARISON</span><b>Best fit for your goal</b></div>{[['Recognition','National','National'],['Result time','45–60 days','30–45 days'],['Exam cycles','2 yearly','4 yearly']].map((r,i)=><div className="compare-line" key={r[0]}><span>{r[0]}</span><b>{r[1]}</b><b className={i>0?'winner':''}>{r[2]}</b></div>)}<div className="compare-labels"><span></span><b>NIOS</b><b>BOSSE</b></div></div></section>
  <footer className="concept-footer"><b>Direction {v.code}: {v.name}</b><span>This is a visual direction study—not the finished product.</span></footer>
  </main>}

function PathCard({icon,n,title,meta,accent}){return <button className={`concept-card ${accent}`}><div><span className="card-num">{n}</span><span className="card-icon">{icon}</span></div><small>{meta}</small><h3>{title}</h3><span className="card-link">Explore this path <ArrowRight/></span></button>}
function HeroVisual({variant}){if(variant==='a')return <div className="editorial-visual"><div className="sun"/><svg viewBox="0 0 560 520"><path className="hill h1" d="M0 410 C100 315 190 360 270 260 C355 154 450 185 560 90 L560 520 L0 520Z"/><path className="hill h2" d="M0 460 C145 385 230 420 350 335 C430 277 500 300 560 246 L560 520 L0 520Z"/><path className="route" d="M50 455 C180 395 238 410 315 322 S420 201 510 132"/></svg><div className="waypoint wp1"><Check/><span><b>Discover</b><small>118 matching options</small></span></div><div className="waypoint wp2"><TrendingUp/><span><b>Compare</b><small>Facts side by side</small></span></div><div className="waypoint wp3"><Sparkles/><span><b>Decide</b><small>With expert guidance</small></span></div></div>;
if(variant==='b')return <div className="atlas-visual"><svg viewBox="0 0 620 520"><defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32"/></pattern></defs><rect width="620" height="520" fill="url(#grid)"/><path className="atlas-route" d="M78 420 C185 420 144 272 275 278 S392 378 458 256 S496 104 565 82"/><circle cx="78" cy="420" r="12"/><circle cx="275" cy="278" r="12"/><circle cx="458" cy="256" r="12"/><circle cx="565" cy="82" r="12"/></svg><span className="atlas-tag at1"><BookOpen/>School<small>10th / 12th</small></span><span className="atlas-tag at2"><GraduationCap/>Degree<small>UG / PG</small></span><span className="atlas-tag at3"><BriefcaseBusiness/>Career<small>First job</small></span><div className="outcome-card"><small>YOUR CURRENT PATH</small><b>Online MBA → Business Analyst</b><span><ShieldCheck/> 6 verified options</span></div></div>;
return <div className="utility-visual"><div className="utility-window"><div className="utility-top"><span/><span/><span/><b>Find your next move</b></div><div className="utility-search"><Search/><span>What do you want to achieve?</span><kbd>⌘ K</kbd></div><div className="utility-grid"><div className="utility-main"><small>BEST MATCH</small><span className="uni-mark">AU</span><h3>Online MBA</h3><p>Amity University Online</p><div><b>₹1.79L</b><span>2 years</span><span>4.8 ★</span></div><button>View program <ArrowRight/></button></div><div className="utility-side"><span><Compass/><b>118</b><small>matches found</small></span><span><ShieldCheck/><b>100%</b><small>verified data</small></span></div></div></div><div className="utility-float"><MapPin/><span><b>Patna</b><small>42 fresh opportunities</small></span></div></div>}
